### ISSUE TITLE
Can't build html

### ISSUE THREAD

**Issue by gmparker2000** [F1LT3R/markserv#27]
Installed markserver, started it, clicked on a ".md" file and get:

 Markserv  error: Can't build HTML:

**Comment by ChBernat** [comment]
Could you provide more detailed info?

**Comment by ChBernat** [comment]
It is now fixed so I'm closing an issue! If you find anything that will disturb you just let us know!

Once again, thanks for reporting an issue.

**Comment by F1LT3R** [comment]
@gmparker2000 fix now published on npm.
It should work now if you re-install... 
`npm install -g markserv` or `npm update -g markserv`
